apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-transcriber-data
  namespace: transcription
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
