apiVersion: v1
kind: Service
metadata:
  name: audio-transcriber-api
  namespace: transcription
spec:
  type: NodePort
  selector:
    app: audio-transcriber-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30800
